### ISSUE TITLE
Command yarn install failling when trying to run Backstage app

### ISSUE THREAD

**Issue by SlavyanaK** [spotify/backstage#1774]
Hello,

I'm trying to run Backstage app on Ubuntu Ubuntu 18.04.4 LTS.

I have node js and npm installed:
$ nodejs -v
v12.18.3
$ npm -v
6.14.6
I also installed yarn.

When I'm cloning backstage repository and trying to run "yarn install", I have the following issue:

backstage$ yarn install
yarn install v1.22.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @spotify/eslint-config-oss@1.0.2" has unmet peer dependency "eslint@>=6".
warning "@spotify/eslint-config-oss > eslint-plugin-notice@0.9.10" has unmet peer dependency "eslint@>=3.0.0".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > example-app > @testing-library/user-event@12.0.7" has unmet peer dependency "@testing-library/dom@>=7.16.0".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > example-app > eslint-plugin-cypress@2.11.1" has unmet peer dependency "eslint@>= 3.2.1".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > @backstage/core > material-table@1.62.0" has unmet peer dependency "@date-io/core@^1.3.6".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/addon-links@5.3.19" has unmet peer dependency "react@*".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/addon-storysource@5.3.19" has unmet peer dependency "@storybook/source-loader@*".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/addon-storysource@5.3.19" has unmet peer dependency "react@*".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/react@5.3.19" has unmet peer dependency "@babel/core@^7.0.1".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/react@5.3.19" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/react@5.3.19" has unmet peer dependency "react@*".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/react@5.3.19" has unmet peer dependency "react-dom@*".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > storybook-dark-mode@0.6.1" has unmet peer dependency "@storybook/api@>= 5.x".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > storybook-dark-mode@0.6.1" has unmet peer dependency "@storybook/components@>= 5.x".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > storybook-dark-mode@0.6.1" has unmet peer dependency "@storybook/core-events@>= 5.x".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > storybook-dark-mode@0.6.1" has unmet peer dependency "@storybook/theming@>= 5.x".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > @backstage/plugin-graphiql > graphiql@1.0.3" has unmet peer dependency "prop-types@>=15.5.0".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > @backstage/cli > @spotify/eslint-config > @spotify/eslint-config-react@7.0.1" has incorrect peer dependency "eslint-plugin-react-hooks@^3.x".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > @backstage/cli > @spotify/eslint-config > @typescript-eslint/eslint-plugin@2.24.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > @backstage/cli > @spotify/eslint-config > @typescript-eslint/parser@2.24.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > @backstage/cli > @spotify/eslint-config > eslint-plugin-jsx-a11y@6.2.3" has incorrect peer dependency "eslint@^3 || ^4 || ^5 || ^6".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > @backstage/cli > @spotify/eslint-config > eslint-plugin-react@7.19.0" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > @backstage/core > material-table > @material-ui/pickers@3.2.10" has unmet peer dependency "@date-io/core@^1.3.6".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/addon-actions > @storybook/api@5.3.19" has unmet peer dependency "regenerator-runtime@*".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/addon-actions > @storybook/components@5.3.19" has unmet peer dependency "react-dom@*".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/addon-actions > @storybook/theming@5.3.19" has unmet peer dependency "react-dom@*".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/addon-links > @storybook/router@5.3.19" has unmet peer dependency "react@*".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/addon-links > @storybook/router@5.3.19" has unmet peer dependency "react-dom@*".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/addon-storysource > react-syntax-highlighter@11.0.2" has unmet peer dependency "react@>= 0.14.0".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/react > @babel/preset-flow@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/react > @storybook/core@5.3.19" has unmet peer dependency "@babel/core@*".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/react > @storybook/core@5.3.19" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/react > @storybook/core@5.3.19" has unmet peer dependency "react@*".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/react > @storybook/core@5.3.19" has unmet peer dependency "react-dom@*".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/react > babel-plugin-named-asset-import@0.3.6" has unmet peer dependency "@babel/core@^7.1.0".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > @backstage/plugin-graphiql > graphiql > codemirror-graphql@0.12.0" has incorrect peer dependency "codemirror@^5.54.0".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > @backstage/plugin-graphql-backend > apollo-server > graphql-subscriptions@1.1.0" has incorrect peer dependency "graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > @backstage/plugin-scaffolder-backend > nodegit > request-promise-native@1.0.8" has unmet peer dependency "request@^2.34".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/addon-actions > @storybook/api > @reach/router@1.3.3" has unmet peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/react > @babel/preset-flow > @babel/plugin-transform-flow-strip-types@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/react > @storybook/core > @babel/plugin-proposal-class-properties@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/react > @storybook/core > @babel/plugin-proposal-object-rest-spread@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > @backstage/plugin-graphql-backend > apollo-server > apollo-server-core > graphql-upload@8.1.0" has incorrect peer dependency "graphql@0.13.1 - 14".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > @backstage/plugin-scaffolder-backend > nodegit > request-promise-native > request-promise-core@1.1.3" has unmet peer dependency "request@^2.34".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/react > @babel/preset-flow > @babel/plugin-transform-flow-strip-types > @babel/plugin-syntax-flow@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-feb97815-2bd0-4e0e-8cd0-8c3b683e4b50 > storybook > @storybook/react > @storybook/core > @babel/plugin-proposal-class-properties > @babel/helper-create-class-features-plugin@7.8.6" has unmet peer dependency "@babel/core@^7.0.0".
[5/5] Building fresh packages...
[1/18] ⠈ husky
[9/18] ⠈ nodegit
[3/18] ⠈ esbuild
[7/18] ⠈ cypress
error /home/Documents/Products/Backstage.io/backstage/node_modules/esbuild: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/Documents/Products/Backstage.io/backstage/node_modules/esbuild
Output:
child_process.js:669
    throw err;
    ^

Error: Command failed: npm install --silent --prefer-offline --no-audit --progress=false esbuild-linux-64@0.6.3
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at installBinaryFromPackage (/home/Documents/Products/Backstage.io/backstage/node_modules/esbuild/install.js:33:17)
    at installOnUnix (/home/Documents/Products/Backstage.io/backstage/node_modules/esbuild/install.js:71:5)
    at Object.<anonymous> (/home/Documents/Products/Backstage.io/backstage/node_modules/esbuild/install.js:117:5)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 13548,

Do you have any idea why it's not working?
Thanks in advance!

**Comment by Rugvip** [comment]
Looks like trouble with installing the esbuild binary. Does the following work or give you a more informative error message?

```sh
npm install --prefer-offline --no-audit --progress=false esbuild-linux-64@0.6.3
```

**Comment by SlavyanaK** [comment]
Here is the output of the command:

npm install --prefer-offline --no-audit --progress=false esbuild-linux-64@0.6.3
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated @mattiasbuelens/web-streams-polyfill@0.2.1: moved to web-streams-polyfill@2.0.0
npm WARN deprecated @hapi/formula@1.2.0: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/pinpoint@1.0.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated @types/testing-library__dom@7.5.0: This is a stub types definition. testing-library__dom provides its own type definitions, so you do not need this installed.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated @hapi/joi@16.1.8: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm WARN rm not removing /home/Documents/Products/Backstage.io/backstage/node_modules/.bin/jest as it wasn't installed by /home/Documents/Products/Backstage.io/backstage/node_modules/jest
npm WARN rm not removing /home/Documents/Products/Backstage.io/backstage/node_modules/.bin/rimraf as it wasn't installed by /home/Documents/Products/Backstage.io/backstage/node_modules/rimraf
npm WARN rm not removing /home/Documents/Products/Backstage.io/backstage/node_modules/.bin/uuid as it wasn't installed by /home/Documents/Products/Backstage.io/backstage/node_modules/uuid
npm WARN rm not removing /home/Documents/Products/Backstage.io/backstage/node_modules/.bin/semver as it wasn't installed by /home/Documents/Products/Backstage.io/backstage/node_modules/semver
npm WARN rm not removing /home/Documents/Products/Backstage.io/backstage/node_modules/.bin/rollup as it wasn't installed by /home/Documents/Products/Backstage.io/backstage/node_modules/rollup
npm WARN rm not removing /home/Documents/Products/Backstage.io/backstage/node_modules/.bin/browserslist as it wasn't installed by /home/Documents/Products/Backstage.io/backstage/node_modules/browserslist
npm WARN rm not removing /home/Documents/Products/Backstage.io/backstage/node_modules/.bin/nopt as it wasn't installed by /home/Documents/Products/Backstage.io/backstage/node_modules/nopt
npm WARN rm not removing /home/Documents/Products/Backstage.io/backstage/node_modules/.bin/mkdirp as it wasn't installed by /home/Documents/Products/Backstage.io/backstage/node_modules/mkdirp
npm WARN rm not removing /home/Documents/Products/Backstage.io/backstage/node_modules/.bin/parser as it wasn't installed by /home/Documents/Products/Backstage.io/backstage/node_modules/@babel/parser
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/@backstage/cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: watchpack-chokidar2@^2.0.0 (node_modules/watchpack/node_modules/watchpack-chokidar2):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.18.3","npm":"6.14.6"})
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/@storybook/core/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/@storybook/react/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @spotify/eslint-config-oss@1.0.2 requires a peer of eslint@>=6 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-notice@0.9.10 requires a peer of eslint@>=3.0.0 but none is installed. You must install peer dependencies yourself.

+ esbuild-linux-64@0.6.3
added 92 packages from 66 contributors, removed 4039 packages and updated 770 packages in 73.61s

39 packages are looking for funding
  run `npm fund` for details

**Comment by Rugvip** [comment]
Ah shite sorry, forgot to tell you to run that in a separate folder ._.

It seems to have worked fine though, maybe the original issue was just some network/npm flakiness. Does the original `yarn install` work? If you ran the npm install in the root of the repo you should be sure to delete the package-lock file and node_modules first.

**Comment by SlavyanaK** [comment]
Ok i found the issue, I ran the command in a separate folder, and in fact it failed because of my npm registry configuration, it was searching inside my company's registry. So i defined the registry to https://registry.npmjs.org/ and now yarn install is working perfectly.
Thanks a lot for your help!

**Comment by Ala0005** [comment]
[1] 2021-05-06T09:41:58.472Z catalog info Locations Refresh: Completed locations refresh in 434ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:43:38.473Z catalog info Locations Refresh: Beginning locations refresh type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:43:38.475Z catalog info Locations Refresh: Visiting 1 locations type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:43:38.475Z catalog info Locations Refresh: Refreshing location bootstrap:bootstrap type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:43:38.745Z catalog info Read 56 entities from location bootstrap:bootstrap in 269ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:43:38.893Z catalog info Wrote 56 entities from location bootstrap:bootstrap in 148ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:43:38.894Z catalog info Locations Refresh: Completed locations refresh in 422ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:45:18.895Z catalog info Locations Refresh: Beginning locations refresh type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:45:18.897Z catalog info Locations Refresh: Visiting 1 locations type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:45:18.897Z catalog info Locations Refresh: Refreshing location bootstrap:bootstrap type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:45:19.314Z catalog info Read 56 entities from location bootstrap:bootstrap in 417ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:45:19.449Z catalog info Wrote 56 entities from location bootstrap:bootstrap in 135ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:45:19.450Z catalog info Locations Refresh: Completed locations refresh in 555ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:46:59.451Z catalog info Locations Refresh: Beginning locations refresh type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:46:59.453Z catalog info Locations Refresh: Visiting 1 locations type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:46:59.454Z catalog info Locations Refresh: Refreshing location bootstrap:bootstrap type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:46:59.763Z catalog info Read 56 entities from location bootstrap:bootstrap in 309ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:46:59.897Z catalog info Wrote 56 entities from location bootstrap:bootstrap in 134ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:46:59.898Z catalog info Locations Refresh: Completed locations refresh in 447ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:48:39.898Z catalog info Locations Refresh: Beginning locations refresh type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:48:39.900Z catalog info Locations Refresh: Visiting 1 locations type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:48:39.900Z catalog info Locations Refresh: Refreshing location bootstrap:bootstrap type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:48:40.162Z catalog info Read 56 entities from location bootstrap:bootstrap in 262ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:48:40.309Z catalog info Wrote 56 entities from location bootstrap:bootstrap in 146ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:48:40.310Z catalog info Locations Refresh: Completed locations refresh in 413ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:50:20.311Z catalog info Locations Refresh: Beginning locations refresh type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:50:20.313Z catalog info Locations Refresh: Visiting 1 locations type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:50:20.313Z catalog info Locations Refresh: Refreshing location bootstrap:bootstrap type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:50:20.676Z catalog info Read 56 entities from location bootstrap:bootstrap in 363ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:50:20.829Z catalog info Wrote 56 entities from location bootstrap:bootstrap in 152ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:50:20.830Z catalog info Locations Refresh: Completed locations refresh in 519ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:52:00.830Z catalog info Locations Refresh: Beginning locations refresh type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:52:00.832Z catalog info Locations Refresh: Visiting 1 locations type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:52:00.833Z catalog info Locations Refresh: Refreshing location bootstrap:bootstrap type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:52:01.132Z catalog info Read 56 entities from location bootstrap:bootstrap in 299ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:52:01.282Z catalog info Wrote 56 entities from location bootstrap:bootstrap in 150ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:52:01.283Z catalog info Locations Refresh: Completed locations refresh in 453ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:53:41.284Z catalog info Locations Refresh: Beginning locations refresh type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:53:41.286Z catalog info Locations Refresh: Visiting 1 locations type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:53:41.286Z catalog info Locations Refresh: Refreshing location bootstrap:bootstrap type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:53:41.575Z catalog info Read 56 entities from location bootstrap:bootstrap in 288ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:53:41.718Z catalog info Wrote 56 entities from location bootstrap:bootstrap in 143ms type=plugin component=catalog-all-locations-refresh
[1] 2021-05-06T09:53:41.719Z catalog info Locations Refresh: Completed locations refresh in 435ms typ





i have installed and started yarn dev and its is still runnning for 3+ hours like above ...pls help... is this correct?

**Comment by timbonicus** [comment]
@Ala0005 Yes, `yarn dev` starts the backend server which runs continuously until you stop it (e.g. with Ctrl-C).

**Comment by freben** [comment]
@Ala0005 put another way - what did you _expect_ to happen? What are you trying to do?

**Comment by Ala0005** [comment]
i am trying to create an react webpage component and getting below error

![Capture](https://user-images.githubusercontent.com/83759429/120134603-1abd7a80-c1ec-11eb-82d0-ef4962988ff1.PNG)

**Comment by Ala0005** [comment]
another error with other application.  Error: Unable to find a publisher for URL: https://github.com/XXXX/backstage.git. Please make sure to register this host under an integration in app-config

**Comment by SangamSid** [comment]
after installing my-backstage-app and then changed the directory and then using the command yarn dev
getting error 
yarn run v1.22.21
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace app start
$ yarn workspace backend start
$ backstage-cli package start
$ backstage-cli package start
[0] 'backstage-cli' is not recognized as an internal or external command,
[0] operable program or batch file.
[1] 'backstage-cli' is not recognized as an internal or external command,
[1] operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
[1] Exit code: 1
[1] Command: C:\Program Files\nodejs\node.exe
[1] Arguments: C:\Users\lenovo\AppData\Roaming\npm\node_modules\yarn\lib\cli.js start
[1] Directory: C:\Users\lenovo\backstage\my-backstage-app\packages\backend
[1] Output:
[1]
info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed.
[0] Exit code: 1
[0] Command: C:\Program Files\nodejs\node.exe
[0] Arguments: C:\Users\lenovo\AppData\Roaming\npm\node_modules\yarn\lib\cli.js start
[0] Directory: C:\Users\lenovo\backstage\my-backstage-app\packages\app
[0] Output:
[0]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[0] yarn start exited with code 1
[1] yarn start-backend exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I request you to guide me step by step. I already spent most of my time in it.
Thanks in advance
