### ISSUE TITLE
[plugin-scaffolder-backend] breaks on try generate in a new project

### ISSUE THREAD

**Issue by angeliski** [spotify/backstage#1874]
When a new project is created using the `@backstage/create-app`, the scaffolder functionality isn't working.
## Expected Behavior
The scaffolder should run without errors

## Current Behavior
The process is interrupted by a error in console.
![winstom-error](https://user-images.githubusercontent.com/1574240/89716695-93192d80-d985-11ea-9709-cc2f407effd4.png) 

## Possible Solution
A possible solution is import winston as namespace, like the #1281 
I will try that and open a PR if works.

## Steps to Reproduce

1. Run a `npx @backstage/create-app`
2. Configure the app frontend to use the [@backstage/plugin-scaffolder](https://www.npmjs.com/package/@backstage/plugin-scaffolder). Repo example: [angeliski/test-backend](https://github.com/angeliski/test-backend/blob/master/packages/app/src/plugins.ts)
3.Start front/backend projects
4. Add a a template to generate. Example:
```
curl \                                                                                                                 
    --location \
    --request POST 'localhost:7000/catalog/locations' \
    --header 'Content-Type: application/json' \
    --data-raw "{\"type\": \"github\", \"target\": \"https://github.com/spotify/cookiecutter-golang/blob/master/template.yaml\"}"
```
5. Try create a new project

## Context
That bug is breaking the software creation templates feature.

Console logs:
```
angeliski@angeliski  /usr/workspace/test-backend/packages/backend   master  yarn start
yarn run v1.22.4
$ backstage-cli backend:dev
Build succeeded
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
info: Beginning locations refresh {"type":"plugin","plugin":"catalog","service":"backstage","timestamp":"2020-08-08T17:54:59.687Z"}
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
info: Visiting 0 locations {"type":"plugin","plugin":"catalog","service":"backstage","timestamp":"2020-08-08T17:54:59.706Z"}
info: Initializing identity API backend {"type":"plugin","plugin":"identity","service":"backstage","timestamp":"2020-08-08T17:54:59.715Z"}
[HPM] Proxy created: /  ->  https://example.com
info: Listening on 0.0.0.0:7000 {"service":"backstage","timestamp":"2020-08-08T17:54:59.729Z"}
info: Beginning locations refresh {"type":"plugin","plugin":"catalog","service":"backstage","timestamp":"2020-08-08T17:55:09.708Z"}
info: Visiting 0 locations {"type":"plugin","plugin":"catalog","service":"backstage","timestamp":"2020-08-08T17:55:09.712Z"}
info: 127.0.0.1 - - [08/Aug/2020:17:55:15 +0000] "POST /catalog/locations HTTP/1.1" 201 2302 "-" "curl/7.68.0"
 {"type":"incomingRequest","service":"backstage","timestamp":"2020-08-08T17:55:15.310Z"}
info: 127.0.0.1 - - [08/Aug/2020:17:55:17 +0000] "GET /catalog/entities?kind=Template&metadata.name=golang-starter HTTP/1.1" 200 - "http://localhost:3000/create/golang-starter" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
 {"type":"incomingRequest","service":"backstage","timestamp":"2020-08-08T17:55:17.791Z"}
info: Beginning locations refresh {"type":"plugin","plugin":"catalog","service":"backstage","timestamp":"2020-08-08T17:55:19.713Z"}
info: Visiting 1 locations {"type":"plugin","plugin":"catalog","service":"backstage","timestamp":"2020-08-08T17:55:19.714Z"}
error: Cannot read property 'combine' of undefined {"type":"errorHandler","service":"backstage","stack":"TypeError: Cannot read property 'combine' of undefined\n    at makeLogStream (webpack-internal:///../../node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:285:29)\n    at JobProcessor.create (webpack-internal:///../../node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:306:39)\n    at eval (webpack-internal:///../../node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:407:30)\n    at handleReturn (/usr/workspace/test-backend/node_modules/express-promise-router/lib/express-promise-router.js:24:27)\n    at /usr/workspace/test-backend/node_modules/express-promise-router/lib/express-promise-router.js:56:9\n    at handleReturn (/usr/workspace/test-backend/node_modules/express-promise-router/lib/express-promise-router.js:24:27)\n    at /usr/workspace/test-backend/node_modules/express-promise-router/lib/express-promise-router.js:56:9\n    at Layer.handle [as handle_request] (/usr/workspace/test-backend/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/workspace/test-backend/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/usr/workspace/test-backend/node_modules/express/lib/router/route.js:112:3)","timestamp":"2020-08-08T17:55:19.966Z"}
info: 127.0.0.1 - - [08/Aug/2020:17:55:19 +0000] "POST /scaffolder/v1/jobs HTTP/1.1" 500 - "http://localhost:3000/create/golang-starter" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"

```

## Your Environment

Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.18.3 - ~/.asdf/installs/nodejs/12.18.3/bin/node
    Yarn: 1.22.4 - ~/.asdf/shims/yarn
    npm: 6.14.6 - ~/.asdf/installs/nodejs/12.18.3/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 79.0
  npmPackages:
    typescript:  3.9.7

**Comment by Rugvip** [comment]
Thank you for the report! Created #1879 to avoid regression.
