### ISSUE TITLE
Failed to Register Bitbucket Private Repository Without Code Changes

### ISSUE THREAD

**Issue by alandovskis** [spotify/backstage#2089]
## Expected Behavior

A new component should appear corresponding to the imported repository.

## Current Behavior

InputError: Failed to read location github https://bitbucket.org/org/android-app/src/develop/catalog-info.yaml, Error: Unable to read github https://bitbucket.org/org/android-app/src/develop/catalog-info.yaml, Error: Incorrect url: https://bitbucket.org/org/android-app/src/develop/catalog-info.yaml, Error: Wrong GitHub URL at HigherOrderOperations.addLocation (webpack-internal:///../../plugins/catalog-backend/src/ingestion/HigherOrderOperations.ts:89:13) at async eval (webpack-internal:///../../plugins/catalog-backend/src/service/router.ts:98:22)

### Hacky Workaround

I was able to import successfully after modifying plugins/register-component/src/components/RegisterComponentPage/RegisterComponentPage.tsx.

I replaced:

`
const data = await catalogApi.addLocation('github', target);
`

with

`
const data = await catalogApi.addLocation('bitbucket/api', target);
`

Although I only tested Bitbucket, this would likely be the case for Gitlab as well.

### Solution 1
Determine the type passed to CatalogApi.addLocation based on the URL:

- https://bitbucket.org/...: bitbucket/api
- https://gitlab.com/...: gitlab/api or gitlab
- https://github.com/...: github

However this solution would not work for GitHub Enterprise, Bitbucket Server and other self-hosted code hosting providers.

### Solution 2

1. Modify the create app script to prompt for the code hosting solution that is being used.
2. Access this value from RegisterComponentPage.tsx

However this would prevent using different code hosting for each component.

## Steps to Reproduce

1. Instance was setup following [Running Backstage Locally](https://backstage.io/docs/getting-started).
1. Browse to Register Existing Component.
2. Paste a URL pointing to a private Bitbucket repository's catalog-info.yaml
3. Click Submit.

## Context

I am trying to import a Bitbucket private repository to see if Backstage could work for me.

## Your Environment

- NodeJS Version (v12): v12.18.3
- Operating System and Version: macOS 10.13.6
- Browser Information: Google Chrome 78.0.3904.70

**Comment by alandovskis** [comment]
This would probably also affect #2081.

**Comment by alandovskis** [comment]
I just tested again following the merge of #2081. It is now working.
