### ISSUE TITLE
TechDocs triggers vulnerable tags warnings in browser console

### ISSUE THREAD

**Issue by timja** [spotify/backstage#2323]
## Expected Behavior

No browser warnings

## Current Behavior

Browser console when viewing techdocs shows:

> Your `allowedTags` option includes, `style`, which is inherently
vulnerable to XSS attacks. Please remove it from `allowedTags`.
Or, to disable this warning, add the `allowVulnerableTags` option
and ensure you are accounting for this risk.

<details>
<summary>Stacktrace</summary>

    at Reader (webpack-internal:///../../plugins/techdocs/src/reader/components/Reader.tsx:43:19)
    at article
    at Content (webpack-internal:///../core/src/layout/Content/Content.tsx:53:3)
    at div
    at Page (webpack-internal:///../core/src/layout/Page/Page.tsx:45:17)
    at TechDocsPageWrapper (webpack-internal:///../../plugins/techdocs/src/reader/components/TechDocsPageWrapper.tsx:32:3)
    at TechDocsPage (webpack-internal:///../../plugins/techdocs/src/reader/components/TechDocsPage.tsx:31:90)
    at Route (webpack-internal:///../../node_modules/react-router/index.js:34:673)
    at Routes (webpack-internal:///../../node_modules/react-router/index.js:37:804)
    at AppRoutes
    at div
    at SidebarPage (webpack-internal:///../core/src/layout/Sidebar/Page.tsx:56:89)
    at Root (webpack-internal:///./src/components/Root/Root.tsx:100:17)
    at Route (webpack-internal:///../../node_modules/react-router/index.js:34:673)
    at Routes (webpack-internal:///../../node_modules/react-router/index.js:37:804)
    at SignInPageWrapper (webpack-internal:///../core-api/src/app/App.tsx:245:18)
    at Router (webpack-internal:///../../node_modules/react-router/index.js:36:23)
    at BrowserRouter (webpack-internal:///../../node_modules/react-router-dom/index.js:63:23)
    at AppRouter (webpack-internal:///../core-api/src/app/App.tsx:256:26)
    at CssBaseline (webpack-internal:///../../node_modules/@material-ui/core/esm/CssBaseline/CssBaseline.js:65:31)
    at WithStyles (webpack-internal:///../../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at ThemeProvider (webpack-internal:///../../node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:42:24)
    at AppThemeProvider (webpack-internal:///../core-api/src/app/AppThemeProvider.tsx:78:29)
    at AppContextProvider (webpack-internal:///../core-api/src/app/AppContext.tsx:31:31)
    at ApiProvider (webpack-internal:///../core-api/src/apis/ApiProvider.tsx:40:24)
    at Provider (webpack-internal:///../core-api/src/app/App.tsx:191:25)
    at App
    at AppContainer (eval at ES6ProxyComponentFactory (webpack-internal:///../../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at HotExportedApp (eval at ES6ProxyComponentFactory (webpack-internal:///../../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)

</details>

## Steps to Reproduce

Start example app up and click view techdocs.
you don't need to actually have it configured

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by timja** [comment]
cc @emmaindal

**Comment by emmaindal** [comment]
@timja Thanks for reporting! 💯   My guess is that this warning is because we sanitize the html but allow the style tag to be able to use the generated styles from mkdocs. We will discuss this further!
