### ISSUE TITLE
Failed to create a buildable app with backstage-cli create-app

### ISSUE THREAD

**Issue by zhyu** [spotify/backstage#489]
I tried to use `backstage-cli create-app` to create a new application, but the created application is not able to build.

## Expected Behavior

* `backstage-cli create-app` command should execute successfully
* the created application should be able to build and start

## Current Behavior

* `backstage-cli create-app` command failed since `yarn build` failed
*  the generated application is not able to build

## Possible Solution

* The `tsconfig.json` of the generated application should contain `"module": "es6"` or other alternatives?
* `<InfoCard maxWidth>` of `packages/cli/templates/default-app/plugins/welcome/src/components/WelcomePage/WelcomePage.tsx` should remove the `maxWidth` property?
* Then I don't know...

## Steps to Reproduce (for bugs)

1. clone `spotify/backstage`
2. `yarn install`
3. `./packages/cli/bin/backstage-cli create-app` 

## Context

1. The `backstage-cli create-app` command failed with error messages:
```
 Building the app:
  executing     yarn install ✔
  executing     yarn build ◞ lerna notice cli v3.20.2
lerna info Executing command in 2 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in 'plugin-welcome'
lerna ERR! yarn run build stdout:
$ backstage-cli plugin:build
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:

Error: Incompatible tsconfig option. Module resolves to 'CommonJS'. This is incompatible with rollup, please use 'module: "ES2015"' or 'module: "ESNext"'.

error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in 'plugin-welcome'
error Command failed with exit code 1.
yarn run v1.22.1
$ lerna run build
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  executing     yarn build ✖

Could not execute command yarn build

It seems that something went wrong when creating the app 🤔
We are going to clean up, and then you can try again.

 Cleanup:
  remove        temporary directory ✔

🔥  Failed to create app!
```
I added `"module": "es6"` to the `tsconfig.json` of the generated application.
2. Run `yarn build` for the generated application, got error:
```
> lerna run build

lerna notice cli v3.20.2
lerna info Executing command in 2 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in 'plugin-welcome'
lerna ERR! yarn run build stdout:
yarn run v1.22.1
$ backstage-cli plugin:build
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:

Error: src/components/WelcomePage/WelcomePage.tsx:39:23 - error TS2322: Type '{ children: Element[]; maxWidth: true; }' is not assignable to type 'IntrinsicAttributes & Props &
 { children?: ReactNode; }'.
  Property 'maxWidth' does not exist on type 'IntrinsicAttributes & Props & { children?: ReactNode; }'.

39             <InfoCard maxWidth>
                         ~~~~~~~~


error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in 'plugin-welcome'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! root@1.0.0 build: `lerna run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the root@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myusername/.npm/_logs/2020-04-07T05_53_48_090Z-debug.log
```
So I removed the `maxWidth` property.
3. `yarn build` again, got error:
```
> lerna run build

lerna notice cli v3.20.2
lerna info Executing command in 2 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in 'plugin-welcome'
lerna ERR! yarn run build stdout:
yarn run v1.22.1
$ backstage-cli plugin:build
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
Circular dependency: ../../node_modules/@backstage/core/dist/cjs/api/index.js -> ../../node_modules/@backstage/core/dist/cjs/api/api.js -> ../../node_modules/@backstage/core/di
st/cjs/api/app/AppBuilder.js -> ../../node_modules/@backstage/core/dist/cjs/icons/index.js -> ../../node_modules/@backstage/core/dist/cjs/icons/icons.js -> ../../node_modules/@
backstage/core/dist/cjs/api/index.js
Circular dependency: ../../node_modules/@backstage/core/dist/cjs/api/index.js -> ../../node_modules/@backstage/core/dist/cjs/api/api.js -> ../../node_modules/@backstage/core/di
st/cjs/api/app/AppBuilder.js -> ../../node_modules/@backstage/core/dist/cjs/icons/index.js -> ../../node_modules/@backstage/core/dist/cjs/icons/icons.js -> /home/yuzhang/worksp
ace/backstage/backstage-demo/node_modules/@backstage/core/dist/cjs/api/index.js?commonjs-proxy -> ../../node_modules/@backstage/core/dist/cjs/api/index.js

Error: 'Component' is not exported by ../../node_modules/react/index.js, imported by ../../node_modules/mini-create-react-context/dist/esm/index.js

error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in 'plugin-welcome'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! root@1.0.0 build: `lerna run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the root@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myusername/.npm/_logs/2020-04-07T05_55_48_810Z-debug.log
```
I'm not sure what happened...

## Your Environment

* NodeJS Version (v12): v12.16.1
* Operating System and Version (e.g. Ubuntu 14.04): Ubuntu 18.04 and macOS 10.13.6
* Browser Information: not relevant

**Comment by Rugvip** [comment]
Thanks for reporting! These issues should be addressed in https://github.com/spotify/backstage/pull/511, so the `alpha.3` release should contain the fixes once it's out.

We're currently working on https://github.com/spotify/backstage/issues/495 to avoid breaking the `create-app` command.

**Comment by braulio-balanza** [comment]
Any suggestions on how to get rid of the circular dependencies?

**Comment by Rugvip** [comment]
@braulio-balanza what circular dependencies?

**Comment by braulio-balanza** [comment]
Hmmm, like ```../../node_modules/@backstage/core/dist/cjs/api/index.js``` referencing itself after a chain of exports in that last error? After some research it seems that node is fine with this, but they sometimes cause problems, like here maybe?

**Comment by zhyu** [comment]
It seems `alpha.3` is released, so I gave it a try:
```
~ npx @backstage/cli create-app
describe is not defined
```

Didn't get enough information to debug, so I tried to run `backstage-cli` from the latest master:
```
~/backstage ./packages/cli/bin/backstage-cli create-app
...
 Building the app:
  executing     yarn install ✔
  executing     yarn build ◠ lerna notice cli v3.20.2
lerna info Executing command in 2 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in 'plugin-welcome'
lerna ERR! yarn run build stdout:
$ backstage-cli plugin:build
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
/home/myusername/backstage/test-app/node_modules/@backstage/cli/dist/index.js:14
describe('dummy', () => {
^

ReferenceError: describe is not defined
    at Object.<anonymous> (/home/myusername/backstage/test-app/node_modules/@backstage/cli/dist/index.js:14:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/myusername/backstage/backstage-demo/node_modules/@backstage/cli/bin/backstage-cli:61:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in 'plugin-welcome'
error Command failed with exit code 1.
yarn run v1.22.1
$ lerna run build
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  executing     yarn build ✖

Could not execute command yarn build

It seems that something went wrong when creating the app 🤔
We are going to clean up, and then you can try again.

 Cleanup:
  remove        temporary directory ✔

🔥  Failed to create app!
```

**Comment by braulio-balanza** [comment]
@zhyu it seems to be a problem with the npm @backstage/cli package. Check #525

**Comment by Rugvip** [comment]
0.1.1-alpha.4 is out with fixes for the above issues and more, please give it a spin :grin:

**Comment by freben** [comment]
Closing for now assuming it is fixed - please reopen if it wasn't solved for you!

**Comment by zhyu** [comment]
Confirmed `npx @backstage/cli create-app` works well now. Thanks!
