### ISSUE TITLE
build is failing on 'Parsing error: The keyword 'export' is reserved'

### ISSUE THREAD

**Issue by moisei** [spotify/backstage#612]
I am trying to build the application but it fails on yarn bundle with following error.
I't tried the master and the v0.1.1-alpha.4 tag - same result.
Please advise.

this is my environment:

```
user@5490f1f4b285:/home/user$ yarn --version
1.22.1
user@5490f1f4b285:/home/user$ npm --version
6.14.4
user@5490f1f4b285:/home/user$ node --version
v12.16.2
user@5490f1f4b285:/home/user$ uname -a
Linux 5490f1f4b285 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 GNU/Linux
user@5490f1f4b285:/home/user$ git status
On branch v0.1.1-alpha.4
```

and here is the failure

```
> yarn install
....
OK
> yarn bundle
....
lerna success run Ran npm script 'build' in 8 packages in 220.2s:
lerna success - @backstage/cli
lerna success - @backstage/core
lerna success - @backstage/test-utils-core
lerna success - @backstage/test-utils
lerna success - @backstage/theme
lerna success - @backstage/plugin-home-page
lerna success - @backstage/plugin-lighthouse
lerna success - @backstage/plugin-welcome
$ backstage-cli app:build
Creating an optimized production build...
Failed to compile.

./src/plugins.ts
  Line 16:1:  Parsing error: The keyword 'export' is reserved

Command 'react-scripts' exited with code 1

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /src/.yarn/releases/yarn-1.22.1.js bundle
Directory: /src/packages/app
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
with --verbose 

```
lerna success - @backstage/plugin-welcome
$ backstage-cli app:build
Creating an optimized production build...
Failed to compile.

./src/plugins.ts
  Line 16:1:  Parsing error: The keyword 'export' is reserved



Command 'react-scripts' exited with code 1

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /src/.yarn/releases/yarn-1.22.1.js bundle
Directory: /src/packages/app
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
verbose 92.322723954 Error: Command failed with exit code 1.
    at /src/.yarn/releases/yarn-1.22.1.js:42956:38
    at Generator.throw (<anonymous>)
    at step (/src/.yarn/releases/yarn-1.22.1.js:543:36)
    at /src/.yarn/releases/yarn-1.22.1.js:558:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
user@5490f1f4b285:/home/user/packages$

```

**Comment by moisei** [comment]
I've just deleted entire folder, cloned the repo and run everything from scratch, and it is not reproduced anymore. probably some glitch on my environment.
